import { BackButton } from "@/components/BackButton";
import { ExternalLink } from "@/components/ExternalLink";
import { DREAM_TWITTER_URL, DREAM_UNISWAP_URL, DREAMCOINS_URL } from "@/lib/constants";
import Image from "next/image";

export default function Page() {
  return (
    <div className="relative flex flex-col items-center w-full min-h-full bg-white font-times text-[#000080]">
      {/* Header */}
      <div className="mt-10 flex flex-col items-center">
        <div className="flex flex-col sm:flex-row items-center">
          <h1 className="text-[36px] sm:text-[48px] md:text-[64px]">
            DREAMFUND <span className="text-xl sm:text-2xl md:text-4xl">INC.</span>
          </h1>

          <div className="ml-3 sm:mt-3.5 flex items-center justify-center bg-[#800080] px-2.5 h-6 md:h-8">
            <p className="text-sm md:text-lg text-white">Coming 2025</p>
          </div>
        </div>
        <p className="mt-4 sm:-mt-2 text-base sm:text-lg">Managing Partner, Agent Dreambags</p>
        <p className="text-base sm:text-lg">Official Home Page</p>
      </div>

      {/* Divider */}
      <div className="h-px w-[calc(100%-80px)] bg-[#000080] my-6 md:my-8 mx-10 shrink-0" />

      {/* Content */}
      <div className="grid grid-cols-1 md:grid-cols-2 mx-5 md:mx-10">
        <div className="flex flex-col items-center gap-5 px-5 sm:px-10">
          <p className="text-lg">Investment thesis</p>
          <p className="text-[15px]">
            DreamFund is the financial engine of the Dream ecosystem. Its purpose is simple: to create a powerful
            treasury that will one day support a thriving network of projects and agents.
          </p>
          <p className="self-start text-[15px]">Here&apos;s how DreamFund grows:</p>
          <p className="text-[15px]">
            Earnings from Dream Projects: Any fees generated by Dream&apos;s projects and agents are funneled directly
            into the fund.
          </p>
          <p className="text-[15px]">
            Partnership Allocations: When curated partners use the Dream Stack to build their agents, DreamFund secures
            a portion of their tokens to expand its treasury. We will be announcing some major partnerships soon.
          </p>
          <p className="text-[15px]">
            Trades by Mr. Dreambags: At the heart of DreamFund is Mr. Dreambags, our managing partner who has been with
            us in stealth for the last 3 months. Dreambag uses real-time data analysis, adaptive learning, and onchain
            analytics to power his decision making.
          </p>
          <p className="text-[15px]">
            Soon, you&apos;ll have the opportunity to stake to become a limited partner in DreamFund. By contributing to
            the fund, you&apos;ll share in the value created as it builds a treasury to power the future of the Dream
            ecosystem. Stay tuned.
          </p>
          <p className="self-start text-[15px]">
            Mr. Dreambags
            <br />
            DREAMFUND INC
            <br />
            First we trade. Then we dream.
          </p>
        </div>

        <div className="flex flex-col pt-10 pb-8 md:pt-14 px-10 sm:px-15 md:px-10">
          <ul className="list-disc space-y-4 md:space-y-6 text-[15px]">
            <li>
              <ExternalLink className="underline" href={process.env.NEXT_PUBLIC_HYPERNETWORK_THESIS_URL || "#"}>
                The Hypernetwork Thesis
              </ExternalLink>
            </li>
            <li>
              <ExternalLink className="underline" href="/agents">
                Dream Corporation org chart
              </ExternalLink>
            </li>
            <li>
              <ExternalLink className="underline" href={DREAMCOINS_URL}>
                Dream token launcher on Base
              </ExternalLink>
            </li>
            <li>
              <ExternalLink className="underline" href={process.env.NEXT_PUBLIC_AGENTS_THESIS_URL || "#"}>
                How Dream will hit 1M agents by 2026
              </ExternalLink>
            </li>
            <li>
              <ExternalLink className="underline" href={DREAM_UNISWAP_URL}>
                Don&apos;t click this one
              </ExternalLink>
            </li>
            <li>
              <ExternalLink className="underline" href={DREAM_TWITTER_URL}>
                Click this one
              </ExternalLink>
            </li>
          </ul>
        </div>
      </div>

      {/* Divider */}
      <div className="h-px w-[calc(100%-80px)] bg-[#000080] my-6 md:my-8 mx-10 shrink-0" />

      {/* Advertisement */}
      <div className="flex flex-col items-center px-10">
        <Image priority alt="dream" src="/images/wordmark-fund.png" height={12} width={110} className="" />
        <p className="mt-4 text-xs sm:text-sm md:text-[15px] text-center">
          BUY DREAM
          <br />
          A COMPANY FOR AGENTS
          <br />
          {process.env.NEXT_PUBLIC_DREAM_TOKEN_ADDRESS || "0x98d59767cd1335071a4e9b9d3482685c915131e8"}
          <br />
          ALWAYS ON — 24/7
        </p>
      </div>

      {/* Divider */}
      <div className="h-px w-[calc(100%-80px)] bg-[#000080] my-6 md:my-8 mx-10 shrink-0" />

      {/* Footer */}
      <p className="text-center text-[15px] mx-10 pb-10">
        If you have any comments about our WEB page, you can write us at the address shown above.
      </p>

      {/* Dismiss */}
      <BackButton className="fixed top-[76px] md:top-22 right-[26px] md:right-10 z-20 bg-[#80008020]" fill="#800080" />
    </div>
  );
}
